apiVersion: v1
kind: Service
metadata:
  name: hangman-service
spec:
  type: LoadBalancer # You can use 'NodePort' if 'LoadBalancer' is not available
  selector:
    app: hangman
  ports:
  - protocol: TCP
    port: 6000 
    targetPort: 5200